export type ResultCategory = "Facelift / Thread Lift" | "Dermal Filler";

export type BeforeAfterItem = {
  id: string;
  url: string;
  category: ResultCategory;
  zone: string;
  description: string;
  alt: string;
};

export const BEFORE_AFTER: BeforeAfterItem[] = [
  {
    id: "07398f9c",
    url: "/__l5e/assets-v1/10078c34-03fe-47bd-b402-f5455cd4d52d/ba-07398f9c-DxADmaDZ.jpg",
    category: "Dermal Filler",
    zone: "Chin",
    description: "A softer, rounder chin was hiding this patient's profile. One syringe of filler gave it a little more shape — enough that the lower face finally looks balanced from the side.",
    alt: "Dermal Filler before and after — Chin at 888clinic",
  },
  {
    id: "07e73527",
    url: "/__l5e/assets-v1/10d0dd40-86e2-4f06-9089-8ef8302ce442/ba-07e73527-ThmdJyUC.jpg",
    category: "Dermal Filler",
    zone: "Chin",
    description: "She wanted a chin that read on camera. A single cc, placed carefully, lengthened it just slightly and the whole jaw looks tidier for it.",
    alt: "Dermal Filler before and after — Chin at 888clinic",
  },
  {
    id: "080b016c",
    url: "/__l5e/assets-v1/cab6806c-58ee-45fb-a975-a4423d168001/ba-080b016c-B4vQM79o.jpg",
    category: "Dermal Filler",
    zone: "Chin",
    description: "The goal here was a longer, V-shaped chin rather than anything dramatic. 1 cc of filler, no downtime, and she went straight back to work.",
    alt: "Dermal Filler before and after — Chin at 888clinic",
  },
  {
    id: "8e89da87",
    url: "/__l5e/assets-v1/f89590ba-f4be-45b3-a98b-b77393ba9c47/ba-8e89da87-E2Jmz6hH.jpg",
    category: "Dermal Filler",
    zone: "Chin",
    description: "Adding a small amount of projection to the chin pulled the lower third of the face into line. Nothing else was treated.",
    alt: "Dermal Filler before and after — Chin at 888clinic",
  },
  {
    id: "99fd5bda",
    url: "/__l5e/assets-v1/679f27da-7069-4e96-8d76-47eda5f2529d/ba-99fd5bda-Bp26B8tP.jpg",
    category: "Dermal Filler",
    zone: "Chin",
    description: "A gentle 1 cc chin augmentation. It smooths the step between lip and chin and makes the profile look more even.",
    alt: "Dermal Filler before and after — Chin at 888clinic",
  },
  {
    id: "f0959737",
    url: "/__l5e/assets-v1/3924c53b-3ec2-4652-8ab1-59d611ec1e85/ba-f0959737-BVOACBfI.jpg",
    category: "Dermal Filler",
    zone: "Chin",
    description: "Filler was used to give the chin a slimmer, slightly longer finish — the kind of change friends notice without knowing why.",
    alt: "Dermal Filler before and after — Chin at 888clinic",
  },
  {
    id: "f2b7571d",
    url: "/__l5e/assets-v1/150eb537-021d-4f30-b8e2-667894120a6c/ba-f2b7571d-G3fyVY34.jpg",
    category: "Dermal Filler",
    zone: "Chin",
    description: "A softer, rounder chin was hiding this patient's profile. One syringe of filler gave it a little more shape — enough that the lower face finally looks balanced from the side.",
    alt: "Dermal Filler before and after — Chin at 888clinic",
  },
  {
    id: "156d40d8",
    url: "/__l5e/assets-v1/c3994f08-1439-4277-9407-3936175ebfbe/ba-156d40d8-DZQh3PQt.jpg",
    category: "Dermal Filler",
    zone: "Lips",
    description: "Her lips had thinned over the years. A conservative amount of filler brought back shape and a softer border, still very much her own mouth.",
    alt: "Dermal Filler before and after — Lips at 888clinic",
  },
  {
    id: "595b26f7",
    url: "/__l5e/assets-v1/71efb6dc-8851-421d-a7ac-e7e604803631/ba-595b26f7-DwRw3_7i.jpg",
    category: "Dermal Filler",
    zone: "Lips",
    description: "We rebuilt a little volume and definition here. She asked for natural, so we stopped early — the smile does the rest.",
    alt: "Dermal Filler before and after — Lips at 888clinic",
  },
  {
    id: "654e8303",
    url: "/__l5e/assets-v1/1f5f98a9-d4d5-41c1-a35a-3c235ef7b41d/ba-654e8303-CAF_T_Yj.jpg",
    category: "Dermal Filler",
    zone: "Lips",
    description: "Lip filler placed to even out the shape rather than to make it bigger. Hydrated, defined, and comfortable within a couple of days.",
    alt: "Dermal Filler before and after — Lips at 888clinic",
  },
  {
    id: "89d45b9d",
    url: "/__l5e/assets-v1/3aa9d0ae-4544-4f5b-a2eb-d29fc339b32f/ba-89d45b9d-B0GBT1Wc.jpg",
    category: "Dermal Filler",
    zone: "Lips",
    description: "A small top-up gave the upper lip a gentle lift and a clearer outline.",
    alt: "Dermal Filler before and after — Lips at 888clinic",
  },
  {
    id: "8aa8f9a5",
    url: "/__l5e/assets-v1/9d4d8de5-8434-42ac-94b4-344f3b0f88fa/ba-8aa8f9a5-BL26o9cn.jpg",
    category: "Dermal Filler",
    zone: "Lips",
    description: "Her lips had thinned over the years. A conservative amount of filler brought back shape and a softer border, still very much her own mouth.",
    alt: "Dermal Filler before and after — Lips at 888clinic",
  },
  {
    id: "9b9be917",
    url: "/__l5e/assets-v1/36b9867a-87f9-4433-886f-0405c44b7cc5/ba-9b9be917-COdQl9Oq.jpg",
    category: "Dermal Filler",
    zone: "Lips",
    description: "We rebuilt a little volume and definition here. She asked for natural, so we stopped early — the smile does the rest.",
    alt: "Dermal Filler before and after — Lips at 888clinic",
  },
  {
    id: "acc31a12",
    url: "/__l5e/assets-v1/ff9befd1-5c5e-4ead-a579-66d6fb614f24/ba-acc31a12-BupIunsW.jpg",
    category: "Dermal Filler",
    zone: "Lips",
    description: "Lip filler placed to even out the shape rather than to make it bigger. Hydrated, defined, and comfortable within a couple of days.",
    alt: "Dermal Filler before and after — Lips at 888clinic",
  },
  {
    id: "cec51db3",
    url: "/__l5e/assets-v1/6433e787-737d-4f8f-93c2-e4e47c940098/ba-cec51db3-D6Y3TuHt.jpg",
    category: "Dermal Filler",
    zone: "Lips",
    description: "A small top-up gave the upper lip a gentle lift and a clearer outline.",
    alt: "Dermal Filler before and after — Lips at 888clinic",
  },
  {
    id: "cecc847e",
    url: "/__l5e/assets-v1/bc8232c0-6eb3-46f4-b765-5aecdb052863/ba-cecc847e-D_PnGZcR.jpg",
    category: "Dermal Filler",
    zone: "Lips",
    description: "Her lips had thinned over the years. A conservative amount of filler brought back shape and a softer border, still very much her own mouth.",
    alt: "Dermal Filler before and after — Lips at 888clinic",
  },
  {
    id: "4bfcd593",
    url: "/__l5e/assets-v1/78f9cb9e-068a-46d3-8986-1fcda3925f41/ba-4bfcd593-DeJvTZzn.jpg",
    category: "Dermal Filler",
    zone: "Under-eyes",
    description: "Threads were placed to lift the tissue that had drifted down over time — the jawline reads sharper immediately, and it keeps settling over the following weeks.",
    alt: "Dermal Filler before and after — Under-eyes at 888clinic",
  },
  {
    id: "066f5d0b",
    url: "/__l5e/assets-v1/c5dba654-c859-4336-b405-b3fe14c0a071/ba-066f5d0b-COgIvpq7.jpg",
    category: "Facelift / Thread Lift",
    zone: "Cheeks & jawline",
    description: "This was about tightening a softening lower face. The lift is visible on the day, with only mild tenderness afterwards.",
    alt: "Facelift / Thread Lift before and after — Cheeks & jawline at 888clinic",
  },
  {
    id: "a2158e30",
    url: "/__l5e/assets-v1/f8290577-f98f-448f-8c96-7723e2d1eb00/ba-a2158e30-vPrT7mIO.jpg",
    category: "Facelift / Thread Lift",
    zone: "Full face & chin",
    description: "A quiet, structural change: the cheek and jaw are supported again, so the face looks rested rather than done.",
    alt: "Facelift / Thread Lift before and after — Full face & chin at 888clinic",
  },
  {
    id: "e6db236f",
    url: "/__l5e/assets-v1/38327453-2f29-449b-a781-5588c04bcb25/ba-e6db236f-CGiUUekw.jpg",
    category: "Facelift / Thread Lift",
    zone: "Full face & jawline",
    description: "Sagging along the jaw was the main concern. After treatment the contour is cleaner and the neckline looks longer.",
    alt: "Facelift / Thread Lift before and after — Full face & jawline at 888clinic",
  },
  {
    id: "4c85406d",
    url: "/__l5e/assets-v1/d8377500-b71f-4ea6-831c-e810dbe714b2/ba-4c85406d-CLDt6Vv2.jpg",
    category: "Facelift / Thread Lift",
    zone: "Full face & lips",
    description: "Threads were placed to lift the tissue that had drifted down over time — the jawline reads sharper immediately, and it keeps settling over the following weeks.",
    alt: "Facelift / Thread Lift before and after — Full face & lips at 888clinic",
  },
  {
    id: "d25e720d",
    url: "/__l5e/assets-v1/c089f8ec-c2bc-42d3-a9b4-2f84c88a9805/ba-d25e720d-DU587fZr.jpg",
    category: "Facelift / Thread Lift",
    zone: "Full face & lips",
    description: "This was about tightening a softening lower face. The lift is visible on the day, with only mild tenderness afterwards.",
    alt: "Facelift / Thread Lift before and after — Full face & lips at 888clinic",
  },
  {
    id: "ba8774c6",
    url: "/__l5e/assets-v1/1d7eb636-b875-4f49-9a8a-91d2525e277a/ba-ba8774c6-wsN-ybVz.jpg",
    category: "Facelift / Thread Lift",
    zone: "Full face & outer eyes",
    description: "A quiet, structural change: the cheek and jaw are supported again, so the face looks rested rather than done.",
    alt: "Facelift / Thread Lift before and after — Full face & outer eyes at 888clinic",
  },
  {
    id: "c254e8c4",
    url: "/__l5e/assets-v1/0f7d9174-dc30-4227-b595-ae7c49c92b9b/ba-c254e8c4-CfzxYWw9.jpg",
    category: "Facelift / Thread Lift",
    zone: "Full face, under-eye & chin",
    description: "Sagging along the jaw was the main concern. After treatment the contour is cleaner and the neckline looks longer.",
    alt: "Facelift / Thread Lift before and after — Full face, under-eye & chin at 888clinic",
  },
  {
    id: "e7059ba3",
    url: "/__l5e/assets-v1/4cc89a16-24fa-45ee-a07f-f9256632cbdc/ba-e7059ba3-CBC4ImlF.jpg",
    category: "Facelift / Thread Lift",
    zone: "Jawline & chin",
    description: "Threads were placed to lift the tissue that had drifted down over time — the jawline reads sharper immediately, and it keeps settling over the following weeks.",
    alt: "Facelift / Thread Lift before and after — Jawline & chin at 888clinic",
  },
  {
    id: "3f0f0b94",
    url: "/__l5e/assets-v1/06c46da1-6536-465e-9d28-922003ab7f0e/ba-3f0f0b94-B6G_QjFL.jpg",
    category: "Facelift / Thread Lift",
    zone: "Jawline & under-eye",
    description: "This was about tightening a softening lower face. The lift is visible on the day, with only mild tenderness afterwards.",
    alt: "Facelift / Thread Lift before and after — Jawline & under-eye at 888clinic",
  },
  {
    id: "9a2dae7f",
    url: "/__l5e/assets-v1/79149e71-4c95-4534-8f10-057a08b04c25/ba-9a2dae7f-CesPSK70.jpg",
    category: "Facelift / Thread Lift",
    zone: "Lips & lower face",
    description: "A quiet, structural change: the cheek and jaw are supported again, so the face looks rested rather than done.",
    alt: "Facelift / Thread Lift before and after — Lips & lower face at 888clinic",
  },
  {
    id: "6f4b2b98",
    url: "/__l5e/assets-v1/0ec7d5de-6c8b-4a35-be85-dc4c9e7832ab/ba-6f4b2b98-DvU3wfN3.jpg",
    category: "Facelift / Thread Lift",
    zone: "Lower face & chin",
    description: "Sagging along the jaw was the main concern. After treatment the contour is cleaner and the neckline looks longer.",
    alt: "Facelift / Thread Lift before and after — Lower face & chin at 888clinic",
  },
  {
    id: "c919e46c",
    url: "/__l5e/assets-v1/777739c8-6a75-476e-8f74-1e65080aa0de/ba-c919e46c-HcpF50W1.jpg",
    category: "Facelift / Thread Lift",
    zone: "Lower face & chin",
    description: "Threads were placed to lift the tissue that had drifted down over time — the jawline reads sharper immediately, and it keeps settling over the following weeks.",
    alt: "Facelift / Thread Lift before and after — Lower face & chin at 888clinic",
  },
  {
    id: "5e1e9ca4",
    url: "/__l5e/assets-v1/c7b6620b-dc71-455e-8d0e-d3f357098ad7/ba-5e1e9ca4-Cb16auGZ.jpg",
    category: "Facelift / Thread Lift",
    zone: "Lower face & jawline",
    description: "This was about tightening a softening lower face. The lift is visible on the day, with only mild tenderness afterwards.",
    alt: "Facelift / Thread Lift before and after — Lower face & jawline at 888clinic",
  },
  {
    id: "d076805a",
    url: "/__l5e/assets-v1/386093f8-24de-4a9a-bc13-7270377cedb8/ba-d076805a-Bcexhu9w.jpg",
    category: "Facelift / Thread Lift",
    zone: "Lower face & jawline",
    description: "A quiet, structural change: the cheek and jaw are supported again, so the face looks rested rather than done.",
    alt: "Facelift / Thread Lift before and after — Lower face & jawline at 888clinic",
  },
];

export const RESULT_CATEGORIES: ResultCategory[] = [
  "Facelift / Thread Lift",
  "Dermal Filler",
];
